services:
  cuber-bot:
    image: sem87sem/cuberbot:latest
    # build: .   # раскомментируйте, если собираете локально
    container_name: cuber-sem
    restart: unless-stopped

    # --- Переменные окружения из файла ---
    env_file:
      - .env.term

    # 🔐 СЕКРЕТЫ И КОНФИГИ (скрытые файлы)
    volumes:
      # --- Сессия Pyrogram  ---
      - ./SEM.session:/app/SEM.session  # файл *.session

      # --- Конфиги ---
      - ./tiker_figi.json:/app/tiker_figi.json

      # --- База данных SQLite ---
      - ./sql_terminator.db:/app/sql_terminator.db

      # --- Логи (вся папка целиком) ---
      - ./log/logs:/app/log/logs

    # 🌐 Переменные окружения
    environment:
      - TZ=Europe/Moscow                         # Часовой пояс (важно для свечей!)

    # 🏥 Health check
    healthcheck:
      test: ["CMD", "python", "-c", "print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s